# 基础知识

## 1. PyTorch基础

### 1.1 Tensor(张量)
多维矩阵，可以看作可以在GPU上运行的numpy数组

In [19]:
import torch
import numpy as np
torch.__version__

'0.4.0'

|表达形式|数据类型|
|-|-|
|torch.Tensor|32位浮点型|
|torch.FloatTensor|32位浮点型|
|torch.DoubleTensor|64位浮点型|
|torch.shortTensor|16位整型|
|torch.IntTensor|32位整型|
|torch.LongTensor|64位整型|

In [30]:
# 创建torch向量
a = torch.Tensor([[2, 3], [4, 8], [7, 9]])   # 默认的是torch.FloatTensor
print('1.Tensor a is:\n', a)
print('2.a shape is:', a.size(), a.shape)    # 可以使用两个方法输出size
print('3.a type is:', type(a))

1.Tensor a is:
 tensor([[ 2.,  3.],
        [ 4.,  8.],
        [ 7.,  9.]])
2.a shape is: torch.Size([3, 2]) torch.Size([3, 2])
3.a type is: <class 'torch.Tensor'>


In [31]:
b = torch.LongTensor([[2, 3], [4, 8], [7, 9]])
print('1.Tensor b is:\n', b)
print('3.a type is:', type(b))

1.Tensor b is:
 tensor([[ 2,  3],
        [ 4,  8],
        [ 7,  9]])
3.a type is: <class 'torch.Tensor'>


In [32]:
# 创建零向量
c = torch.zeros([3,2])   # 3*2的零向量
print('1.Tensor c is:\n', c)

1.Tensor c is:
 tensor([[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]])


In [33]:
# 创建符合高斯分布的随机数据
d = torch.randn([3,2])
print('1.Tensor d is:\n', d)

1.Tensor d is:
 tensor([[ 0.2971,  0.5337],
        [ 0.4952, -0.7407],
        [-0.1089, -1.1817]])


In [70]:
a = torch.Tensor([[2, 3], [4, 8], [7, 9]]) 
print('1.Tensor a is:\n', a)
a[0, 1] = 77      # a[0][1] = 77，两种方式都可以进行数组元素的改写
print('2.Tensor new a is:\n', a)

1.Tensor a is:
 tensor([[ 2.,  3.],
        [ 4.,  8.],
        [ 7.,  9.]])
2.Tensor new a is:
 tensor([[  2.,  77.],
        [  4.,   8.],
        [  7.,   9.]])


In [77]:
# torch.Tensor和numpy.array之间互相转换
a = torch.Tensor([[2, 3], [4, 8], [7, 9]]) 
# print('0.{} a is:\n{}'.format(type(a), a))
numpy_a = a.numpy()            # 转换为numpy的数组
print('1.convert Tensor to {} is:\n{}'.format(type(numpy_a), numpy_a))
numpy_e = np.array([[1,2,3],[4,5,6]])
# print('2.{} e is:\n{}'.format(type(numpy_e), numpy_e))
e = torch.from_numpy(numpy_e)   # 转换为pytorch的Tensor
print('2.from numpy to {} is:\n{}'.format(type(e), e))
f_torch_e = e.float()           # pytorch的Tensor类型转换为float
print('3.{} is:\n{}'.format(type(f_torch_e), f_torch_e))

1.convert Tensor to <class 'numpy.ndarray'> is:
[[2. 3.]
 [4. 8.]
 [7. 9.]]
2.from numpy to <class 'torch.Tensor'> is:
tensor([[ 1,  2,  3],
        [ 4,  5,  6]], dtype=torch.int32)
3.<class 'torch.Tensor'> is:
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])


In [78]:
# pytorch支持GPU
a = torch.Tensor([[2, 3], [4, 8], [7, 9]])
if torch.cuda.is_available():
    a_cuda = a.cuda()
    print(a_cuda)

小结:
- `torch变量.numpy()` pytorch的tensor转换为numpy的array
- `torch.from_numpy(numpy变量)` numpy的array转换为pytorch的tensor
- `torch变量.X类型()` pytorch的tensor转换为相应的X类型

### 1.2 Variable(变量)
Variable与Tensor类似，但Variable会放到计算图中，然后进行前向传播、后向传播和自动求导

|属性|作用|
|-|-|
|data|Variable里的tensor数值|
|grad|Variable的反向传播梯度|
|grad_fn|得到Variable的操作|

In [95]:
# 1. 对标量求导
from torch.autograd import Variable
# 创建变量，求导需要传入requires_grad参数，默认为False
x = Variable(torch.Tensor([2]), requires_grad=True)   # Tensor变为Variable
w = Variable(torch.Tensor([3]), requires_grad=True)
b = Variable(torch.Tensor([4]), requires_grad=True)

# 构建计算图
y = w * x + b

# 计算梯度
y.backward()   # 对所有需要梯度的变量求导，标量求导不需要参数

# 输出梯度
print('1.输出梯度')
print('x的梯度:', x.grad)
print('w的梯度:', w.grad)
print('b的梯度:', b.grad)

1.输出梯度
x的梯度: tensor([ 3.])
w的梯度: tensor([ 2.])
b的梯度: tensor([ 1.])
None


In [98]:
# 2. 对矩阵求导
x = torch.randn([3,2])
x = Variable(x, requires_grad=True)


torch.Size([3, 2])